import { Facebook, Github, Instagram, Linkedin, Twitter } from "lucide-react";

// web services each tile data
const services = [
  {
    cta: "Get Portfolio",
    title: "Personal",
    slug: "personal",
    image: "/personal.png",
    features: [
      "Fast & optimized",
      "Custom Domain Connection",
      "Free SSL",
      "SEO friendly",
      "Premium support",
      "Tailored customization",
      "Personalized optimization",
    ],
    desc: "Unleash the power of personalization. From customization to optimization, I cater to your specific requirements, delivering results that exceed expectations.",
  },
  {
    cta: "Elevate Your Brand",
    title: "Corporate",
    slug: "corporate",
    image: "/corporate.png",
    features: [
      "Fast & optimized",
      "Custom Domain Connection",
      "Free SSL",
      "SEO friendly",
      "Premium support",
      "Seamless integration",
      "Enterprise-level solutions",
    ],
    desc: "Elevate your business with corporate solutions tailored to your needs. From seamless integration to unparalleled support, I ensure your enterprise operates at its peak efficiency.",
  },
  {
    cta: "Start Selling",
    title: "Ecommerce",
    slug: "ecommerce",
    image: "/ecommerce.png",
    features: [
      "Fast & optimized",
      "Custom Domain Connection",
      "Free SSL",
      "SEO friendly",
      "Premium support",
      "Boost digital presence",
      "Foster growth",
    ],
    desc: "Dive into the world of online commerce with Ecommerce solutions, designed to boost your digital presence and foster growth.",
  },
  {
    cta: "Create Your Vision",
    title: "Custom",
    slug: "custom",
    image: "/custom.png",
    features: [
      "Fast & optimized",
      "Custom Domain Connection",
      "Free SSL",
      "SEO friendly",
      "Premium support",
      "Creative solutions",
      "Expertise-driven development",
    ],
    desc: "From concept to execution, my custom development services provide the foundation for your startup's success, combining creativity, expertise, and unparalleled support.",
  },
  {
    cta: "Launch Your Project",
    title: "Deployment",
    slug: "deployment",
    image: "/deployment.png",
    features: [
      "Fast & optimized",
      "Custom Domain Connection",
      "Free SSL",
      "SEO friendly",
      "Premium support",
      "Hassle-free deployment",
      "Project maintenance",
    ],
    desc: "If you're looking for someone to deploy and maintain your project, then you're in a right place! You can leave it for me and get rid of extra work.",
  },
];

// projects each tile data
const projects = [
  {
    title: "GateTak",
    tagline: "City-wide delivery & logistics platform for Haripur",
    slug: "gatetak",
    images: ["/projects/aban-edu-1.png", "/projects/aban-edu-2.png", "/projects/aban-edu-3.png"],
    keywords: ["React Native", "Next.js", "Supabase", "TypeScript", "Logistics", "Mobile"],
    repo: "",
    link: "",
    startedOn: "Jul-2026",
    completedOn: "Present",
    summary: "Founded GateTak, a city-wide delivery and logistics platform featuring 3 separate React Native mobile apps (Customers, Riders, Vendors) and a Next.js admin panel.",
    desc: "## GateTak — Delivery & Logistics Startup\n\nGateTak is a city-wide delivery and logistics platform founded for Haripur, Pakistan. Built as a full-stack lead across web and mobile.\n\n### Key Highlights:\n- Engineered 3 separate React Native mobile applications for **Customers**, **Riders**, and **Vendors/Restaurants**.\n- Built a centralized Supabase database for real-time tracking, order state transitions, and user account management.\n- Developed an admin control panel using Next.js for operational oversight, managing vendors, rider payouts, and live order status.",
  },
  {
    title: "AWC Veterinary Ordering Platform",
    tagline: "B2B veterinary compounding pharmacy e-commerce",
    slug: "awc-veterinary-platform",
    images: ["/projects/awc-2.png", "/projects/awc-3.png", "/projects/awc-4.png", "/projects/awc-5.png", "/projects/awc-1.png"],
    keywords: ["Next.js", "React.js", "PostgreSQL", "Prisma", "RBAC", "B2B Workflows"],
    repo: "",
    link: "",
    startedOn: "Oct-2025",
    completedOn: "Jun-2026",
    summary: "A B2B veterinary ordering platform with clinic management, prescriptions, and order workflows for 50+ clinics, reducing manual processing by ~40%.",
    desc: "## AWC Veterinary Ordering Platform\n\nAnimal Welfare Compounding (AWC) Platform is a B2B e-commerce system for a veterinary compounding pharmacy in Australia. Veterinarians register clinics, order compounded medications including quality-assured products and custom made-to-order formulations, and manage prescriptions for animal patients.\n\n### Key Highlights:\n- Built a clinic-first ordering platform serving 50+ clinics, reducing manual processing time by ~40%.\n- Developed a dynamic pricing engine supporting clinic-specific pricing rules and product-level overrides.\n- Implemented secure JWT authentication with granular role-based access control (RBAC) for admins and clinic staff.",
  },
  {
    title: "Astra Wellness Telehealth",
    tagline: "Phase 1 telehealth platform for doctors and patients",
    slug: "astra-wellness-telehealth",
    images: ["/projects/astra-1.png", "/projects/astra-2.png", "/projects/astra-3.png", "/projects/astra-4.png", "/projects/astra-5.png"],
    keywords: ["Next.js", "Telehealth", "Appointments", "Video Consultations", "Chat", "AI Transcription"],
    repo: "",
    link: "https://astra-wellness-platform-764800041404.us-central1.run.app/",
    startedOn: "Jan-2026",
    completedOn: "Jun-2026",
    summary: "A telehealth platform covering doctor onboarding, patient booking, appointment requests, video consultations, chat, and AI medical summaries.",
    desc: "## Astra Wellness Telehealth — Phase 1\n\nA telehealth web application with doctor and patient roles. Doctors can register, manage professional profiles, select medical categories and specialties, upload certifications, define availability, accept or reject appointments, conduct video consultations, and chat with patients.\n\n### Key Highlights:\n- Category-based doctor discovery, calendar availability management, and appointment status tracking.\n- In-meeting video calls and text chat integration for seamless remote consultations.\n- AI-powered medical transcription and automated consultation summary generation.",
  },
  {
    title: "Bonny",
    tagline: "Events, subscriptions, and QR voucher redemption",
    slug: "bonny",
    images: ["/projects/bonny-0.png", "/projects/bonny-1.png", "/projects/bonny-2.png", "/projects/bonny-3.png", "/projects/bonny-4.png", "/projects/bonny-5.png", "/projects/bonny-6.png"],
    keywords: ["React.js", "Next.js", "TypeScript", "Supabase", "Stripe", "QR Code"],
    repo: "",
    link: "https://bonny.at",
    startedOn: "Feb-2025",
    completedOn: "Jun-2025",
    summary: "An event discovery and voucher management app serving customers, businesses, and super admins with QR redemption and Stripe payments.",
    desc: "## Bonny — Events & Voucher Platform\n\nBonny is a Next.js web application for event discovery and voucher management built at Inostrik. It serves three distinct user roles: regular users, businesses, and super admins.\n\n### Key Highlights:\n- Supabase backend for real-time data storage and dynamic content management.\n- QR-based voucher redemption system for instant in-person verification.\n- Subscription tier management and Stripe payment integration.",
  },
  {
    title: "Nigotis",
    tagline: "Accounting Software & SME Business Management System",
    slug: "nigotis",
    images: [
      "/nigotis-3.png",
      "/nigotis-1.png",
      "/nigotis-2.png",
      "/nigotis-4.png",
      "/nigotis-5.png",
    ],
    keywords: [
      "Next.js",
      "React.js",
      "MongoDB",
      "Node.js",
      "TailwindCSS",
      "Framer Motion",
      "AWS S3",
      "RBAC",
    ],
    repo: "",
    link: "https://nigotis-fe.vercel.app/",
    startedOn: "Oct-2024",
    completedOn: "Jan-2025",
    summary: "A full accounting and business management system covering invoicing, payroll processing, asset tracking, and RBAC for SME clients.",
    desc: "## Nigotis - Accounting Software & Business Automation System\n\nBuilt at Raqqamiyya (Dubai, UAE), Nigotis is a web-based accounting and business management system for SMEs.\n\n### Key Highlights:\n- Module engineering for invoicing, payroll processing, employee records, and asset tracking.\n- Role-Based Access Control (RBAC) with secure authentication for multi-user organizational workflows.\n- Optimized SSR and tuned MongoDB aggregation queries to handle large financial ledger datasets with ultra-low latency.\n\n**Test Credentials:**\n- Email: abdullah@justxtech.com\n- Password: 12345678",
  },
  {
    title: "Sehat-AI",
    tagline: "Deep learning chest X-ray screening system",
    slug: "sehat-ai",
    images: ["/projects/sehat-ai-0.png", "/projects/sehat-ai-1.png", "/projects/sehat-ai-1.jpg", "/projects/sehat-ai-2.jpg"],
    keywords: ["Python", "FastAPI", "DenseNet121", "React Native", "Expo", "CNN"],
    repo: "",
    link: "",
    startedOn: "Jan-2025",
    completedOn: "2026",
    summary: "Deep learning chest X-ray screening pipeline for TB and Pneumonia using DenseNet121 transfer learning, FastAPI backend, and React Native mobile app.",
    desc: "## Sehat-AI — Deep Learning Medical Screening\n\nMedical AI system created as a flagship project, combining deep learning with real-time mobile API delivery.\n\n### Key Highlights:\n- Trained a deep learning image classification pipeline with DenseNet121 transfer learning for TB and Pneumonia detection.\n- Built a high-performance FastAPI server serving real-time prediction endpoints.\n- Developed a React Native mobile application for clinicians and patients to upload X-rays and instantly view diagnostic confidence scores.",
  },
  {
    title: "Aban Edu",
    tagline: "Multi-tenant SaaS school management system",
    slug: "aban-edu",
    images: ["/projects/aban-edu-1.png", "/projects/aban-edu-2.png", "/projects/aban-edu-3.png", "/projects/aban-edu-4.png", "/projects/aban-edu-5.png"],
    keywords: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "SaaS", "Multi-tenant"],
    repo: "",
    link: "",
    startedOn: "Jan-2026",
    completedOn: "Present",
    summary: "A multi-tenant school management SaaS with isolated tenant data, fee voucher automation, role-based security, and React Native guardian app.",
    desc: "## Aban Edu — Multi-Tenant School SaaS\n\nArchitected a scalable SaaS system for educational institutions.\n\n### Key Highlights:\n- Complex relational schema designed in PostgreSQL using Prisma ORM for multi-branch school isolation.\n- Features timetables, automated fee voucher generation, attendance logging, and academic marksheets.\n- Created a React Native guardian application prototype for live attendance alerts and fee reminders.",
  },
  {
    title: "Dynam Galaxy",
    tagline: "High-animation agency portfolio website",
    slug: "dynam-galaxy",
    images: ["/dynam-1.png", "/dynam-2.png", "/dynam-3.png"],
    keywords: [
      "Next.js",
      "React.js",
      "TailwindCSS",
      "Framer Motion",
      "GSAP",
      "Magic UI",
    ],
    repo: "",
    link: "https://www.dynamgalaxy.com/",
    startedOn: "Sep-2024",
    completedOn: "Sep-2024",
    desc: "## Dynam Galaxy - Agency Portfolio\n\nBuilt at Inostrik as a high-animation agency portfolio for Dynam Galaxy, showcasing custom UI design, responsive animations, and fast SSR performance using Next.js and Framer Motion.",
  },
  {
    title: "Naseerfolio",
    tagline: "Portfolio site for Flutter Mobile App Developer",
    slug: "naseerfolio",
    images: [
      "/naseerfolio-1.gif",
      "/naseerfolio-2.gif",
      "/naseerfolio-image.jpg",
    ],
    keywords: [
      "Next.js",
      "React.js",
      "TailwindCSS",
      "Framer Motion",
      "Nodemailer",
    ],
    repo: "",
    link: "https://protech-coders.com/",
    startedOn: "Jun-2024",
    completedOn: "Jun-2024",
    desc: "## Naseerfolio - Developer Portfolio\n\nSleek, high-performance portfolio website built for Muhammad Naseer, a Flutter mobile developer, featuring interactive project previews, smooth Framer Motion micro-interactions, and integrated contact API.",
  },
  {
    title: "Activus",
    tagline: "Technology agency platform with 3D graphics & animations",
    slug: "activus",
    keywords: [
      "Next.js",
      "React.js",
      "TailwindCSS",
      "Framer Motion",
      "Spline 3D",
      "GSAP",
    ],
    images: ["/activus.png"],
    repo: "",
    link: "https://activus1.vercel.app",
    startedOn: "Jul-2024",
    completedOn: "Jul-2024",
    desc: "## Activus - Tech Agency Showcase\n\nCreated an interactive agency website integrating Spline 3D graphics, GSAP scroll triggers, and Framer Motion layout transitions.",
  },
  {
    title: "Read Verve",
    tagline: "Full stack blogging platform with RBAC & comments",
    slug: "read-verve",
    images: ["/read-verve.gif", "/read-verve-sm.png"],
    keywords: ["Next.js", "React.js", "Node.js", "MongoDB"],
    repo: "https://github.com/just-abdullah-dev/read-verve-next-js/",
    link: "",
    startedOn: "Sep-2023",
    completedOn: "Nov-2023",
    desc: "## Read Verve - Dynamic Content Platform\n\nFull stack blogging application featuring user profiles, article categorization, interactive comment threads, and multi-admin management.",
  },
  {
    title: "Skill Joiner",
    tagline: "University skill marketplace & student forum hub",
    slug: "skill-joiner",
    images: ["/skill-joiner-1.gif", "/skill-joiner-2.gif"],
    keywords: ["Next.js", "React.js", "Node.js", "MongoDB"],
    repo: "https://github.com/just-abdullah-dev/skill-joiner-nextjs",
    link: "",
    startedOn: "Dec-2023",
    completedOn: "Jan-2024",
    desc: "## Skill Joiner - PAF-IAST Platform\n\nA talent matching platform created for university students to publish service offerings, bid on freelance jobs, and collaborate in peer forums.",
  },
  {
    title: "Quizical",
    tagline: "Interactive trivia & knowledge quiz app",
    slug: "quizical",
    images: ["/quizical.gif"],
    keywords: ["React.js", "Trivia API"],
    repo: "https://github.com/just-abdullah-dev/Quizical-App",
    link: "https://quizical-app.netlify.app/",
    startedOn: "Sep-2023",
    completedOn: "Sep-2023",
    desc: "## Quizical App\n\nInteractive React quiz application featuring custom difficulty settings, category selections, immediate scoring, and API data fetching.",
  },
  {
    title: "Tenzies Game",
    tagline: "Fast-paced interactive dice matching game",
    slug: "tenzies",
    images: ["/tenzies.gif"],
    keywords: ["React.js", "LocalStorage"],
    repo: "https://github.com/just-abdullah-dev/Tenzies-Game",
    link: "https://tenzies-game-ar.netlify.app/",
    startedOn: "Sep-2023",
    completedOn: "Sep-2023",
    desc: "## Tenzies Game\n\nClean React game with state tracking for dice rolls, best time persistence, and victory celebration animations.",
  },
];

// skills list
const skills = [
  { title: "Next.js", category: "Frontend", level: "Production" },
  { title: "React.js", category: "Frontend", level: "Production" },
  { title: "TypeScript", category: "Languages", level: "Production" },
  { title: "JavaScript", category: "Languages", level: "Production" },
  { title: "Python", category: "Languages", level: "Applied" },
  { title: "Tailwind CSS", category: "Frontend", level: "Production" },
  { title: "Framer Motion", category: "Frontend", level: "Production" },
  { title: "React Native", category: "Mobile", level: "Production" },
  { title: "Expo", category: "Mobile", level: "Production" },
  { title: "Node.js", category: "Backend", level: "Production" },
  { title: "Express.js", category: "Backend", level: "Production" },
  { title: "FastAPI", category: "Backend", level: "Production" },
  { title: "Nest.js", category: "Backend", level: "Applied" },
  { title: "PostgreSQL", category: "Database", level: "Production" },
  { title: "Prisma ORM", category: "Data", level: "Production" },
  { title: "MongoDB", category: "Database", level: "Production" },
  { title: "Supabase", category: "Backend", level: "Production" },
  { title: "MySQL", category: "Database", level: "Production" },
  { title: "REST APIs", category: "Expertise", level: "Production" },
  { title: "SaaS Architecture", category: "Expertise", level: "Production" },
  { title: "RBAC & Auth", category: "Security", level: "Production" },
  { title: "Docker & AWS S3", category: "Tools", level: "Applied" },
  { title: "Git & Vercel", category: "Tools", level: "Production" },
];

// Main Work Experience (as defined in CV)
const workExperience = [
  {
    role: "Founder | Full Stack Engineer",
    company: "GateTak - On-site",
    location: "Haripur, Pakistan",
    period: "Jul 2026 – Present",
    type: "Delivery Startup",
    highlights: [
      "Founded GateTak, a city-wide delivery and logistics platform for Haripur, building three separate React Native apps for customers, riders, and vendors/restaurants, backed by a Supabase database.",
      "Built the admin panel in Next.js for managing orders, vendors, and riders across the platform.",
      "Serving as full stack engineer across the entire stack, web and mobile.",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "Peregrine Ventures AI - Contract, Remote",
    location: "Lightsview, South Australia",
    period: "Oct 2025 – Jun 2026",
    type: "Healthtech & AI",
    highlights: [
      "Built a B2B veterinary ordering platform with clinic management, prescriptions, and order workflows for 50+ clinics, reducing manual processing by ~40%.",
      "Developed a dynamic pricing engine supporting clinic-specific pricing rules and product-level overrides.",
      "Built a telehealth platform with booking, video calls, chat, AI transcription, and automated visit summaries.",
      "Implemented secure JWT authentication with role-based access for admins and clinic users.",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "Inostrik - Part-time, Remote",
    location: "Islamabad, Pakistan",
    period: "Feb 2025 – Jun 2025",
    type: "Client Products",
    highlights: [
      "Delivered a Supabase-powered CMS with dynamic blog and banner management, and Bonny, a full events and voucher management platform: admin dashboard, QR-based redemption, user/business/event management, and subscription tier features using Next.js, TypeScript, and Supabase.",
      "Improved SSR and database query strategies, cutting page load times across CMS-heavy pages.",
    ],
  },
  {
    role: "Full Stack Developer",
    company: "Raqqamiyya (Nigotis) - Part-time, Remote",
    location: "Dubai, UAE",
    period: "Oct 2024 – Jan 2025",
    type: "SME Accounting System",
    highlights: [
      "Built a full accounting and business management system covering invoicing, payroll processing, and asset tracking for SME clients.",
      "Established RBAC with secure authentication, ensuring granular access per user role across the platform.",
      "Used SSR and tuned MongoDB queries to handle large ledger datasets with low latency.",
    ],
  },
  {
    role: "Web Developer",
    company: "Inostrik - Part-time, Remote",
    location: "Islamabad, Pakistan",
    period: "Sep 2024",
    type: "Agency Web",
    highlights: [
      "Built Dynam Galaxy, a high-animation agency portfolio site, using Next.js and Framer Motion.",
    ],
  },
];

// Internships (moved after main work experience)
const internships = [
  {
    role: "Software Engineer Intern",
    company: "Mahhir 360 - On-site Internship",
    location: "Lahore, Pakistan",
    period: "Jul 2025 – Sep 2025",
    type: "Restaurant SaaS",
    highlights: [
      "Built an internal task tracker for a multi-branch restaurant chain to coordinate employees across different cities, laying the groundwork for a future employee performance tracking feature.",
      "Built the Supabase-powered backend for the internal task manager, handling data models and APIs for task assignment across restaurant branches.",
    ],
  },
  {
    role: "Frontend Developer Intern",
    company: "Powersoft19 - On-site Internship",
    location: "Lahore, Pakistan",
    period: "Jul 2024 – Aug 2024",
    type: "Healthcare System",
    highlights: [
      "Created and refined reusable UI components for a healthcare management system using React and Tailwind CSS.",
      "Raised key screen rendering performance and accessibility through component refactoring in collaboration with senior developers.",
    ],
  },
];

const productsToLaunch = [
  {
    name: "GateTak",
    status: "Founding Lead",
    accent: "green",
    desc: "City-wide delivery & logistics platform for Haripur with 3 React Native apps (Customers, Riders, Vendors) & Next.js admin panel.",
  },
  {
    name: "Aban Edu",
    status: "Building",
    accent: "orange",
    desc: "A multi-tenant school management SaaS with fee automation, roles, and PostgreSQL-first architecture.",
  },
  {
    name: "Aban Arena",
    status: "Soon",
    accent: "gray",
    desc: "A mobile-first arena booking product for availability, reservations, payments, and sports venue operations.",
  },
  {
    name: "Sehat-AI",
    status: "FYP",
    accent: "gray",
    desc: "AI-assisted chest X-ray screening workflow powered by DenseNet121 CNN models, FastAPI backend, and mobile app.",
  },
];

const learningFocus = [
  "Retrieval-Augmented Generation (RAG)",
  "Production AI API Design & DenseNet Pipelines",
  "Scalable Multi-Tenant SaaS & RBAC",
  "Mobile Product Delivery with React Native & Expo",
];

const education = {
  institute: "Pak-Austria Fachhochschule (PAF-IAST), Haripur, KPK",
  period: "Oct 2022 – May 2026",
  degree: "Bachelor of Software Engineering (CGPA: 3.47)",
  cgpa: "3.47",
  highlights: [
    "Dean's List recipient — recognized 4 consecutive times for top GPA performance.",
    "Teaching Assistant for 7 courses across 4 semesters: Programming Fundamentals, ICT, DSA, Calculus, Applied Physics, Computer Networks, Discrete Structures.",
    "Relevant Coursework: Deep Learning, Computer Networks, Database Systems, Software Engineering, Algorithms, Discrete Structures.",
  ],
};

const achievements = [
  "Dean's List - 4x at PAF-IAST for maintaining top GPA performance each semester.",
  "Full Merit Scholarship - Granted for one semester based on outstanding academic results.",
  "Half Merit Scholarship - Received for one semester for sustained academic achievement.",
  "Prime Minister Laptop Award - Government of Pakistan PM Laptop Scheme, presented to top-performing students nationwide.",
];

// socials links
const social_links = [
  {
    jsx: <Linkedin className={"text-gray-500 hover:text-white"} />,
    link: "https://www.linkedin.com/in/just-abdullah-/",
  },
  { jsx: <Github className={"text-gray-500 hover:text-white"} />, link: "https://github.com/just-abdullah-dev" },
  { jsx: <Twitter className={"text-gray-500 hover:text-white"} />, link: "https://twitter.com/just_abdullah_3" },
  { jsx: <Instagram className={"text-gray-500 hover:text-white"} />, link: "https://instagram.com/just_abdullah_._" },
  {
    jsx: <Facebook className={"text-gray-500 hover:text-white"} />,
    link: "https://www.facebook.com/profile.php?id=100063930870228",
  },
];

const reviews = [
  {
    name: "ABDUL RAHMAN ASIM",
    profession: "Founder & CEO of Dynam Galaxy",
    avatar: "/asim.jpg",
    projectSlug: "dynam-galaxy",
    review: `I have worked with a bunch of developers for the Dynam Galaxy website, but none could get it right until Abdullah stepped in. The guy is an absolute Next.js genius. He pulled off what others couldn’t, with insane dedication, problem-solving skills, and next-level expertise.

Honestly, I was losing hope after hiring multiple devs, but Abdullah just made it happen. He handled every challenge like a pro and delivered a site that’s not just functional but super smooth, fast, and exactly how I envisioned it.

If you need a Website especially Next.js expert who actually delivers, Abdullah is your guy. Can’t recommend him enough!
`,
  },
  {
    name: "MUHAMMAD NASEER",
    profession: "Flutter Mobile App Developer",
    avatar: "/naseer.jpeg",
    projectSlug: "naseerfolio",
    review: `I'm absolutely delighted with the exceptional work Abdullah has done on my portfolio website! The final result exceeded my expectations in every way. The website is not only visually stunning, but also incredibly functional and user-friendly. Abdullah demonstrated a remarkable understanding of my vision and requirements, and his attention to detail and expertise in web development are truly impressive. The website is a testament to his creativity, professionalism, and dedication to delivering high-quality work. I couldn't be happier with the outcome and would highly recommend Abdullah to anyone seeking a talented and reliable web developer.`,
  },
  {
    name: "Hayan Khan",
    profession: "Senior React Developer",
    avatar: "/hayan.jpg",
    projectSlug: "activus",
    review: `Working with Abdullah was a wonderful experience, I was looking for a developer to do one of my extra project and I cannot trust everyone with my work but Abdullah always went the extra mile, did everything on time and had a very creative and optimized approach from start to end. He has a very good design eye. I am looking forward to future collaborations with him. Much recommended!`,
  },
];

export {
  services,
  social_links,
  projects,
  skills,
  reviews,
  workExperience,
  internships,
  productsToLaunch,
  learningFocus,
  education,
  achievements,
};
